# For Linux and macOS - allow undefined symbols as they'll be resolved by PHP
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-undefined-version"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-undefined-version"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

# For Windows - use rust-lld linker for compatibility
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
